### ISSUE TITLE
Why not vanilla awesome bar.

### ISSUE THREAD

**Issue by ashin-15** [NTBBloodbath/dotfiles#1]
Hello I was just wondering how the hell did u make the ur bar look like a beauty. That's when I saw polybar. So my question is why not use awesomewm bar.

**Comment by NTBBloodbath** [comment]
Hi, I was already a bspwm user before moving to awesome so I had an existing polybar setup and I didn't wanted to configure wibar (awesomewm bar) from scratch since it could take a long time for me 'cause the docs are just huge and the widgets collection for wibar is really big too.

That's why I decided to use polybar, basically trying to avoid an unnecessary learning curve with wibar because polybar already has everything I need.

However I think I should move to wibar sooner or later because polybar systray module is buggy so it doesn't hide on fullscreen lol

**Comment by ashin-15** [comment]
MM. I see.  It is a little scary to configure wibar
